plugin: amazon.aws.aws_ec2
regions:
  - us-east-2
filters:
  instance-state-name: [running]
  tag:Ansible: "True"
hostnames:
  - ip-address
keyed_groups:
  - key: tags.Ansible
    prefix: ""
    separator: ""
# Ce bloc force l'utilisateur ubuntu pour tout le groupe
compose:
  ansible_user: "ubuntu"
