---
- name: Install Node.js
  apt:
    name: nodejs
    state: present
    update_cache: yes

- name: Copy sample app
  copy:
    src: app.js  # Ici, Ansible cherchera automatiquement dans le dossier 'files' du rÃ´le
    dest: /home/ubuntu/app.js
    owner: ubuntu
    group: ubuntu
    mode: 0755

- name: Start sample app
  shell: "nohup node /home/ubuntu/app.js > /home/ubuntu/app.log 2>&1 &"
  args:
    chdir: /home/ubuntu/
    creates: /home/ubuntu/app.log
